/**
 * GeminiCoachCard.tsx — Gemini AI Warrior Coach & Self-Mastery Advisor
 *
 * Implements:
 *   1. Real-time archetype-tailored daily coaching directive & motivation
 *   2. Urge Countermeasure Tactical Protocol generated by Gemini AI
 *   3. Interactive "Ask Warrior Coach" real-time advisor
 *   4. Direct Gemini API Key configuration support + robust offline reasoning fallback
 */

import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Bot,
  Send,
  RefreshCw,
  Key,
  ShieldCheck,
  ChevronRight,
  Flame,
  CheckCircle2
} from 'lucide-react';
import { db } from '../../services/db';
import { geminiService } from '../../services/geminiService';
import { GeminiCoachInsight, UserProfile } from '../../types';

export const GeminiCoachCard: React.FC = () => {
  const [profile, setProfile] = useState<UserProfile>(db.getProfile());
  const [insight, setInsight] = useState<GeminiCoachInsight | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [query, setQuery] = useState<string>('');
  const [coachResponse, setCoachResponse] = useState<string | null>(null);
  const [askingCoach, setAskingCoach] = useState<boolean>(false);

  /* ── API Key modal state ─────────────────────────────────────────── */
  const [showKeyModal, setShowKeyModal] = useState<boolean>(false);
  const [apiKeyInput, setApiKeyInput] = useState<string>(geminiService.getApiKey());
  const [keySaved, setKeySaved] = useState<boolean>(false);

  useEffect(() => {
    const unsub = db.subscribe(() => {
      setProfile(db.getProfile());
    });

    // Load or generate today's insight
    loadDailyInsight();

    return () => unsub();
  }, [profile.selectedArchetype]);

  const loadDailyInsight = async () => {
    const existing = db.getCoachInsights().find((i) => i.date === new Date().toISOString().split('T')[0]);
    if (existing) {
      setInsight(existing);
    } else {
      await handleGenerateInsight();
    }
  };

  const handleGenerateInsight = async () => {
    setLoading(true);
    try {
      const newInsight = await geminiService.generateDailyInsight();
      setInsight(newInsight);
    } finally {
      setLoading(false);
    }
  };

  const handleAskCoach = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setAskingCoach(true);
    setCoachResponse(null);
    try {
      const response = await geminiService.askWarriorCoach(query);
      setCoachResponse(response);
    } finally {
      setAskingCoach(false);
    }
  };

  const handleSaveApiKey = (e: React.FormEvent) => {
    e.preventDefault();
    geminiService.setApiKey(apiKeyInput);
    setKeySaved(true);
    setTimeout(() => {
      setKeySaved(false);
      setShowKeyModal(false);
      handleGenerateInsight();
    }, 1200);
  };

  return (
    <div className="md3-card-tinted" style={{ padding: '20px', position: 'relative' }}>
      {/* ── Header ─────────────────────────────────────────────────── */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <div style={{
            width: '36px',
            height: '36px',
            borderRadius: 'var(--md-sys-shape-full)',
            background: 'var(--md-sys-color-primary)',
            color: 'var(--md-sys-color-on-primary)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            boxShadow: '0 4px 12px rgba(0,0,0,0.15)'
          }}>
            <Sparkles size={20} />
          </div>
          <div>
            <span className="md3-section-title" style={{ fontSize: '10px' }}>GEMINI 1.5 PRO COACH</span>
            <h2 style={{ fontSize: '16px', fontWeight: 800, color: 'var(--md-sys-color-on-primary-container)' }}>
              Warrior Intelligence Directive
            </h2>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '6px' }}>
          <button
            type="button"
            onClick={handleGenerateInsight}
            disabled={loading}
            className="md3-button-tonal md3-button-sm"
            style={{ padding: '0 10px', height: '30px' }}
            title="Regenerate daily insight"
          >
            <RefreshCw size={13} className={loading ? 'animate-spin' : ''} />
          </button>

          <button
            type="button"
            onClick={() => setShowKeyModal(true)}
            className="md3-button-tonal md3-button-sm"
            style={{ padding: '0 10px', height: '30px' }}
            title="Configure Gemini API Key"
          >
            <Key size={13} />
          </button>
        </div>
      </div>

      {/* ── Daily Directive & Quote ─────────────────────────────────── */}
      {insight && (
        <div style={{ marginTop: '16px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {/* Stoic Quote Pill */}
          <div style={{
            background: 'rgba(255, 255, 255, 0.75)',
            backdropFilter: 'blur(10px)',
            borderRadius: 'var(--md-sys-shape-medium)',
            padding: '14px',
            boxShadow: '0 2px 8px rgba(0,0,0,0.03)'
          }}>
            <div style={{ fontSize: '10px', fontWeight: 800, textTransform: 'uppercase', color: 'var(--md-sys-color-primary)', letterSpacing: '0.5px' }}>
              Daily Sovereign Motto
            </div>
            <p style={{ fontSize: '13px', fontStyle: 'italic', fontWeight: 700, marginTop: '4px', lineHeight: 1.4 }}>
              "{insight.quote}"
            </p>
          </div>

          {/* Actionable Challenge Directive */}
          <div style={{
            background: '#ffffff',
            borderRadius: 'var(--md-sys-shape-medium)',
            padding: '14px',
            boxShadow: '0 2px 8px rgba(0,0,0,0.03)'
          }}>
            <div style={{ fontSize: '10px', fontWeight: 800, textTransform: 'uppercase', color: 'var(--md-sys-color-primary)', letterSpacing: '0.5px' }}>
              ⚡ Today's Execution Challenge
            </div>
            <p style={{ fontSize: '13px', fontWeight: 600, marginTop: '4px', lineHeight: 1.4, color: 'var(--md-sys-color-on-surface)' }}>
              {insight.dailyDirective}
            </p>
          </div>

          {/* Urge Defusal Tactical Protocol */}
          <div style={{
            background: 'var(--md-sys-color-secondary-container)',
            borderRadius: 'var(--md-sys-shape-medium)',
            padding: '14px',
            color: 'var(--md-sys-color-on-secondary-container)'
          }}>
            <div style={{ fontSize: '10px', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              🛡️ Urge Defusal Countermeasure
            </div>
            <p style={{ fontSize: '12px', fontWeight: 600, marginTop: '4px', lineHeight: 1.4 }}>
              {insight.urgeStrategy}
            </p>
          </div>
        </div>
      )}

      {/* ── Interactive Ask Warrior Coach Input ─────────────────────── */}
      <div style={{ marginTop: '16px' }}>
        <form onSubmit={handleAskCoach} style={{ display: 'flex', gap: '8px' }}>
          <input
            type="text"
            placeholder="Ask coach (e.g. 'feeling an urge', 'low motivation')..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="md3-field-outlined"
            style={{ height: '40px', padding: '0 14px', fontSize: '13px', flex: 1 }}
          />
          <button
            type="submit"
            disabled={askingCoach}
            className="md3-button-filled md3-button-sm"
            style={{ height: '40px', padding: '0 16px', flexShrink: 0, fontWeight: 800 }}
          >
            {askingCoach ? <RefreshCw size={14} className="animate-spin" /> : <Send size={14} />}
          </button>
        </form>

        {coachResponse && (
          <div style={{
            marginTop: '12px',
            padding: '14px',
            background: '#ffffff',
            borderRadius: 'var(--md-sys-shape-medium)',
            fontSize: '13px',
            lineHeight: 1.5,
            color: 'var(--md-sys-color-on-surface)',
            boxShadow: '0 4px 14px rgba(0,0,0,0.06)',
            whiteSpace: 'pre-line'
          }}>
            <div style={{ fontSize: '10px', fontWeight: 800, color: 'var(--md-sys-color-primary)', textTransform: 'uppercase', marginBottom: '4px' }}>
              🦅 Gemini Warrior Coach Response:
            </div>
            {coachResponse}
          </div>
        )}
      </div>

      {/* ── API Key Configuration Scrim Modal ──────────────────────── */}
      {showKeyModal && (
        <div className="md3-scrim" onClick={() => setShowKeyModal(false)}>
          <div className="md3-dialog" onClick={(e) => e.stopPropagation()}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Key size={20} color="var(--md-sys-color-primary)" />
              <h3 style={{ fontSize: '18px', fontWeight: 800 }}>Gemini API Settings</h3>
            </div>

            <p style={{ fontSize: '12px', color: 'var(--md-sys-color-on-surface-variant)', lineHeight: 1.4 }}>
              Enter your Google AI Studio Gemini API Key for live real-time LLM reasoning. (Leave blank to use the built-in offline knowledge reasoning engine).
            </p>

            <form onSubmit={handleSaveApiKey} style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <input
                type="password"
                placeholder="AIzaSy..."
                value={apiKeyInput}
                onChange={(e) => setApiKeyInput(e.target.value)}
                className="md3-field-outlined"
                style={{ fontFamily: 'monospace' }}
              />

              {keySaved && (
                <div style={{ fontSize: '12px', color: 'var(--md-sys-color-tertiary)', fontWeight: 700 }}>
                  ✓ API Key configuration saved!
                </div>
              )}

              <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end', marginTop: '8px' }}>
                <button
                  type="button"
                  onClick={() => setShowKeyModal(false)}
                  className="md3-button-text"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="md3-button-filled"
                >
                  Save Key
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
